# Generated by Django 4.2.11 on 2024-05-17 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Laptop", "0008_remove_order_buyer_email_remove_order_buyer_name_and_more"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        ("account", "0005_emailaddress_idx_upper_email"),
        ("secondapp", "0002_rename_user_data_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="User_Data",
        ),
    ]
