# Generated by Django 4.2.11 on 2024-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secondapp", "0003_rename_user_user_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_data",
            name="favourite_place",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
