# Generated by Django 5.0.2 on 2024-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Laptop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="os",
            field=models.CharField(max_length=40),
        ),
    ]
