# Generated by Django 5.0.2 on 2024-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Laptop", "0002_alter_laptop_os"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="full_processor_details",
            field=models.CharField(max_length=100),
        ),
    ]
