# Generated by Django 4.2.11 on 2024-03-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Laptop", "0004_rename_image_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="main_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product_image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="p_image",
                to="Laptop.laptop",
            ),
        ),
    ]
