# Generated by Django 4.2.11 on 2024-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Laptop", "0005_laptop_main_img_alter_product_image_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="main_img",
            field=models.ImageField(upload_to=""),
        ),
    ]
