# Generated by Django 4.2.11 on 2024-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Laptop", "0006_alter_laptop_main_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prouct_id", models.IntegerField()),
                ("buyer_name", models.CharField(max_length=30)),
                ("buyer_email", models.CharField(max_length=30)),
            ],
        ),
    ]
